Repository AndyTauber/andy-infra, pull requests merged in 2022-08, with the labels that each got.

#53 rebuild code
  config/jobs/andy-infra/andy-infra-presubmit.yaml
  config/prow/cluster/test-pods_namespace.yaml
  config/prow/config.yaml
  infra/gcp/configs/secrets/cluster-secret-store-prow.yaml
  infra/gcp/configs/secrets/cluster-secret-store-test-pods.yaml
  infra/gcp/configs/secrets/external-secrets-prow.yaml
  infra/gcp/configs/secrets/external-secrets-test-pods.yaml
  infra/gcp/configs/secrets/prow-build-cluster-secret-store-default.yaml
  infra/gcp/configs/secrets/prow-build-cluster-secret-store-test-pods.yaml
  infra/gcp/configs/secrets/prow-build-external-secrets-test-pods.yaml
  infra/gcp/configs/secrets/prow-service-cluster-secret-store-default.yaml
  tools/kubeconfig-builder-job/deploy/cluster/cronjob.yaml
  tools/kubeconfig-builder-job/deploy/deploy.sh
Labels: approved, size/L

#54 Adding Aman as owner
  OWNERS
Labels: size/XS, needs-ok-to-test, do-not-merge/invalid-owners-file

#55 [WIP] Create extended-support-periodics.yaml
  config/jobs/extended-support/extended-support-periodics.yaml
Labels: size/M, needs-ok-to-test, do-not-merge/work-in-progress

#56 Update extended-support-periodics.yaml
  config/jobs/extended-support/extended-support-periodics.yaml
Labels: size/XS, needs-ok-to-test

#57 Tce tests running using prow job
  config/jobs/tce/tce-tests-in unmanaged cluster-testing-presubmit.yaml
Labels: approved, size/S

#58 tce-prow-job-testing
  config/jobs/tce/tce-testing-presubmit.yaml
Labels: approved, size/XS

#59 TCE: Fix test spec
  config/jobs/tce/tce-testing-presubmit.yaml
Labels: approved, size/XS, lgtm

#60 Add kubeconfig for TKG ES cluster
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/prow-controller-manager_deployment.yaml
  config/prow/cluster/sinker_deployment.yaml
Labels: approved, size/M, lgtm

#62 Enable workload identiy and split clusters configuration
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/crier_rbac.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/deck_rbac.yaml
  config/prow/cluster/ghproxy_deployment.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/hook_rbac.yaml
  config/prow/cluster/horologium_deployment.yaml
  config/prow/cluster/prow-controller-manager_deployment.yaml
  config/prow/cluster/prow-controller-manager_rbac.yaml
  config/prow/cluster/sinker_deployment.yaml
  config/prow/cluster/sinker_rbac.yaml
  config/prow/cluster/statusreconciler_deployment.yaml
  config/prow/cluster/tide_deployment.yaml
  config/prow/config.yaml
Labels: approved, size/M, lgtm

#61 Update extended-support-periodics.yaml
  config/jobs/extended-support/extended-support-periodics.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#66 Add a heartbeat job
  config/jobs/extended-support/canaries.yaml
Labels: approved, size/S

#65 Update extended-support-periodics.yaml
  config/jobs/extended-support/extended-support-periodics.yaml
Labels: approved, size/M, needs-ok-to-test

#68 Es master blocking jobs
  config/jobs/extended-support/extended-support-k8s-periodics.yaml
  config/jobs/extended-support/extended-support-periodics.yaml
Labels: size/M, needs-ok-to-test
