Repository AndyTauber/andy-infra, pull requests merged in 2022-07, with the labels that each got.

#43 [Do Not Merge] new sample presubmit with pubsub test
  config/jobs/test-infratest-job.yaml
Labels: size/S

#44 update config
  config/jobs/andy-infra/andy-infra-postsubmit-trusted.yaml
  config/jobs/andy-infra/andy-infra-presubmit.yaml
  config/jobs/andy-prow/andy-prow-postsubmit.yaml
  config/jobs/andy-prow/andy-prow-presubmit.yaml
  config/jobs/test-infra/andy-infra.trusted.master.yaml
  config/jobs/test-infra/postsubmits.yaml
  config/jobs/test-prow/print-test.yaml
  config/prow/cluster-issuer.yaml
  config/prow/cluster/backend-config-iap.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/ingress.yaml
  config/prow/cluster/managed-cert.yaml
  config/prow/config.yaml
  config/prow/contour-values.yaml
  config/prow/external-secrets.yaml
Labels: approved, size/L

#45 newsecrets
  infra/gcp/bash/02_build_prow_on_gcp.sh
  infra/gcp/bash/build-prow-on-gcp.sh
  infra/gcp/bash/configure-iap.md
  infra/gcp/bash/prod-env.txt
  infra/gcp/bash/sandbox-env.txt
  infra/gcp/configs/jobs-variable/build-images/build.yaml
  infra/gcp/configs/jobs-variable/tanzu-test-infra/postsubmit-trusted.yaml
  infra/gcp/configs/jobs-variable/tanzu-test-infra/postsubmits.yaml
  infra/gcp/configs/jobs-variable/tanzu-test-infra/presubmits.yaml
  infra/gcp/configs/jobs-variable/tce/periodics.yaml
  infra/gcp/configs/prow-variable/autobump-config/prow-component-autobump-config.yaml
  infra/gcp/configs/prow-variable/boskos/README.md
  infra/gcp/configs/prow-variable/boskos/boskos-resources.yaml
  infra/gcp/configs/prow-variable/boskos/cleaner.yaml
  infra/gcp/configs/prow-variable/boskos/crd.yaml
  infra/gcp/configs/prow-variable/boskos/janitor.yaml
  infra/gcp/configs/prow-variable/boskos/kustomization.yaml
  infra/gcp/configs/prow-variable/boskos/namespace.yaml
  infra/gcp/configs/prow-variable/boskos/patch-aws-account/job.yaml
  infra/gcp/configs/prow-variable/boskos/patch-aws-account/rbac.yaml
  infra/gcp/configs/prow-variable/boskos/rbac.yaml
  infra/gcp/configs/prow-variable/boskos/reaper.yaml
  infra/gcp/configs/prow-variable/boskos/resource-configmap.yaml
  infra/gcp/configs/prow-variable/cluster/crier_deployment.yaml
  infra/gcp/configs/prow-variable/cluster/crier_rbac.yaml
  infra/gcp/configs/prow-variable/cluster/deck_deployment.yaml
  infra/gcp/configs/prow-variable/cluster/deck_rbac.yaml
  infra/gcp/configs/prow-variable/cluster/ghproxy_deployment.yaml
  infra/gcp/configs/prow-variable/cluster/hook_deployment.yaml
  infra/gcp/configs/prow-variable/cluster/hook_rbac.yaml
  infra/gcp/configs/prow-variable/cluster/horologium_deployment.yaml
  infra/gcp/configs/prow-variable/cluster/horologium_rbac.yaml
  infra/gcp/configs/prow-variable/cluster/ingress.yaml
  infra/gcp/configs/prow-variable/cluster/managed-cert.yaml
  infra/gcp/configs/prow-variable/cluster/prow-controller-manager_deployment.yaml
  infra/gcp/configs/prow-variable/cluster/prow-controller-manager_rbac.yaml
  infra/gcp/configs/prow-variable/cluster/sinker_deployment.yaml
  infra/gcp/configs/prow-variable/cluster/sinker_rbac.yaml
  infra/gcp/configs/prow-variable/cluster/statusreconciler_deployment.yaml
  infra/gcp/configs/prow-variable/cluster/statusreconciler_rbac.yaml
  infra/gcp/configs/prow-variable/cluster/test-pods_namespace.yaml
  infra/gcp/configs/prow-variable/cluster/tide_deployment.yaml
  infra/gcp/configs/prow-variable/cluster/tide_rbac.yaml
  infra/gcp/configs/prow-variable/config.yaml
  infra/gcp/configs/prow-variable/job-seed.yaml
  infra/gcp/configs/prow-variable/plugins.yaml
  infra/gcp/configs/secrets/cluster-secret-store-prow.yaml
  infra/gcp/configs/secrets/cluster-secret-store-test-pods.yaml
  infra/gcp/configs/secrets/external-secrets-prow.yaml
  infra/gcp/configs/secrets/external-secrets-test-pods.yaml
  infra/gcp/configs/secrets/prow-build-cluster-secret-store-test-pods.yaml
  infra/gcp/configs/secrets/prow-build-external-secrets-test-pods.yaml
  infra/gcp/ingress-iap/backend-config-iap.yaml
  infra/gcp/ingress-iap/deck-svc.yaml
  infra/gcp/utils/config-bootstrap-job.yaml
Labels: approved, size/XXL

#46 newsecrets
  tools/kubeconfig-builder-job/.gitignore
  tools/kubeconfig-builder-job/Dockerfile
  tools/kubeconfig-builder-job/README.md
  tools/kubeconfig-builder-job/deploy/cluster/clusterrole.yaml
  tools/kubeconfig-builder-job/deploy/cluster/cronjob.yaml
  tools/kubeconfig-builder-job/deploy/deploy.sh
  tools/kubeconfig-builder-job/go.mod
  tools/kubeconfig-builder-job/go.sum
  tools/kubeconfig-builder-job/install.sh
  tools/kubeconfig-builder-job/main.go
  tools/kubeconfig-builder-job/pkg/gcloud/secretmanager.go
  tools/kubeconfig-builder-job/pkg/kubernetes/client.go
  tools/kubeconfig-builder-job/pkg/kubernetes/kubeconfig.go
  tools/kubeconfig-builder-job/pkg/kubernetes/serviceaccount.go
  tools/kubeconfig-builder-job/pkg/utility/constants/constants.go
  tools/kubeconfig-builder-job/pkg/utility/utility.go
Labels: approved

#47 add new ESO secrets for kubeconfig
  infra/gcp/configs/secrets/prow-build-cluster-secret-store-default.yaml
  infra/gcp/configs/secrets/prow-build-external-secrets-default.yaml
Labels: approved, size/M

#50 Updating owner
  OWNERS
  config/jobs/to-be-deleted.yaml
Labels: size/S, needs-ok-to-test, do-not-merge/invalid-owners-file
